import React from "react";

export default function BackgroundBanner() {
  return (
    <div className="background-container">
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <div className="pink-text">
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
        <h1>MELISSA RICH NYC</h1>
      </div>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
      <h1>MELISSA RICH NYC</h1>
    </div>
  );
}
